// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tw.Data;

#nullable disable

namespace tw.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoriaVideojuego", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("VideojuegosVideojuegoId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasCategoriaId", "VideojuegosVideojuegoId");

                    b.HasIndex("VideojuegosVideojuegoId");

                    b.ToTable("CategoriaVideojuego");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "48dfad57-b484-46f3-a0af-7ffab24448aa",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "9ef73af5-94ff-41b9-9c4f-d5bf0b20b61d",
                            Name = "Usuario",
                            NormalizedName = "USUARIO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6a893ddd-709d-4fc3-9873-0acc4b0d1994",
                            RoleId = "48dfad57-b484-46f3-a0af-7ffab24448aa"
                        },
                        new
                        {
                            UserId = "da65c0e2-c3de-4225-9007-b1f7947e99d5",
                            RoleId = "9ef73af5-94ff-41b9-9c4f-d5bf0b20b61d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tw.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Disparos",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Aventura",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Deportes",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nombre = "Terror",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nombre = "Peleas",
                            Protegida = true
                        });
                });

            modelBuilder.Entity("tw.Models.CustomIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Protegido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6a893ddd-709d-4fc3-9873-0acc4b0d1994",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dcec328b-2616-4b03-a811-9e8e576c7b20",
                            Email = "zS20018182@estudiantes.uv.mx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Nombre = "Bernardo julian marin sanchez",
                            NormalizedEmail = "ZS20018182@ESTUDIANTES.UV.MX",
                            NormalizedUserName = "ZS20018182@ESTUDIANTES.UV.MX",
                            PasswordHash = "AQAAAAIAAYagAAAAEHgSEUlxgaaMWQrmSSqzCEUtmvLjkgU4jGNTrM158wspILxKIXMI5aZvrli1nM+v/g==",
                            PhoneNumberConfirmed = false,
                            Protegido = true,
                            SecurityStamp = "0dd0b866-29bc-49c2-8e3a-cc3e49321d72",
                            TwoFactorEnabled = false,
                            UserName = "zS20018182@estudiantes.uv.mx"
                        },
                        new
                        {
                            Id = "da65c0e2-c3de-4225-9007-b1f7947e99d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f83f6da6-65a9-4193-9de2-77571898e8e7",
                            Email = "bernardojulianmarinsanchez0@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Nombre = "usuario juli",
                            NormalizedEmail = "BERNARDOJULIANMARINSANCHEZ0@GMAIL.COM",
                            NormalizedUserName = "BERNARDOJULIANMARINSANCHEZ0@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELzJ1ucdl2q/+a3tFW6ys7meHVlJffU6AXLB3GUWNg0+ogUHf+eJIQxq0mQVeyXs7A==",
                            PhoneNumberConfirmed = false,
                            Protegido = false,
                            SecurityStamp = "e2c51297-60ac-4a90-bfad-13d9352fc4be",
                            TwoFactorEnabled = false,
                            UserName = "bernardojulianmarinsanchez0@gmail.com"
                        });
                });

            modelBuilder.Entity("tw.Models.Videojuego", b =>
                {
                    b.Property<int>("VideojuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VideojuegoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VideojuegoId");

                    b.ToTable("Videojuego");

                    b.HasData(
                        new
                        {
                            VideojuegoId = 1,
                            Anio = 2017,
                            Descripcion = "La trama comienza con el personaje principal, el Guardian, que es un miembro de la Alianza de los Guardianes, una organización que protege la Tierra y el universo de la amenaza del Imperio de los Caballeros de la Luz.",
                            Poster = "https://m.media-amazon.com/images/I/71mJCznfFcL._AC_SX569_.jpg",
                            Titulo = "Destinity 2"
                        },
                        new
                        {
                            VideojuegoId = 2,
                            Anio = 2021,
                            Descripcion = "En esta nueva entrega, el jefe Maestro, el gran héroe de la humanidad y personaje principal de la saga, se enfrentará a un grupo sanguinario y temible conocido como los Desterrados",
                            Poster = "https://m.media-amazon.com/images/I/81nWynmiDPL._AC_SL1500_.jpg",
                            Titulo = "Halo infinite"
                        },
                        new
                        {
                            VideojuegoId = 3,
                            Anio = 2023,
                            Descripcion = "El juego se centra en partidas por equipos en mapas con un entorno destructible, donde se anima a los jugadores a utilizar el entorno dinámico a su favor",
                            Poster = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/header.jpg?t=1714660383",
                            Titulo = "The Finals"
                        },
                        new
                        {
                            VideojuegoId = 4,
                            Anio = 2020,
                            Descripcion = " es un shooter en primera persona frenético y ultraviolento, inspirado en los mejores FPS de los 90 tanto en el apartado artístico como en cuanto a mecánicas. Su mantra: la humanidad está muerta, la sangre es combustible, el infierno está lleno.",
                            Poster = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1229490/header.jpg?t=1704406135",
                            Titulo = "Ultrakill"
                        },
                        new
                        {
                            VideojuegoId = 5,
                            Anio = 2016,
                            Descripcion = "Overwatch 2 es un juego de acción en equipo gratuito ambientado en un futuro optimista en el que todas las partidas presentan una refriega definitiva 5c5. Juega como una luchadora por la libertad que salta en el tiempo, ",
                            Poster = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg?t=1715731747",
                            Titulo = "Overwatch 2"
                        },
                        new
                        {
                            VideojuegoId = 6,
                            Anio = 2014,
                            Descripcion = "El combate en Black Desert Online se basa en la acción, requiriendo puntería manual similar a aquellos encontrados en videojuegos de disparos en tercera persona. Las habilidades pueden activarse a través de uso de combos para atacar, esquivando o bloqueando.",
                            Poster = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582660/header.jpg?t=1715716651",
                            Titulo = "Black Desert online"
                        },
                        new
                        {
                            VideojuegoId = 7,
                            Anio = 2023,
                            Descripcion = "Su trama por lo general describe las heroicas aventuras del joven guerrero Link, que debe enfrentarse a peligros y resolver acertijos para ayudar a la Princesa Zelda a derrotar a Ganondorf y salvar su hogar, el reino de Hyrule.",
                            Poster = "https://m.media-amazon.com/images/I/71glcphYY0L.__AC_SX300_SY300_QL70_ML2_.jpg",
                            Titulo = "The Legend of zelda"
                        },
                        new
                        {
                            VideojuegoId = 8,
                            Anio = 2022,
                            Descripcion = ". La historia sigue al personaje del jugador, un Sinluz, que es un miembro de un grupo de exiliados que han sido convocados de vuelta a las Tierras Intermedias después de la Guerra de la Devastación.",
                            Poster = "https://m.media-amazon.com/images/I/71GPiuyNtkL.__AC_SX300_SY300_QL70_ML2_.jpg",
                            Titulo = "Elden ring"
                        },
                        new
                        {
                            VideojuegoId = 9,
                            Anio = 2015,
                            Descripcion = "La historia principal tiene lugar en el año 2287, 10 años después de los eventos de Fallout 3 y 210 años después de La Gran Guerra, que causó devastación nuclear catastrófica. ",
                            Poster = "https://m.media-amazon.com/images/I/812nlgWkM6L.__AC_SX300_SY300_QL70_ML2_.jpg",
                            Titulo = "Fallout 4"
                        },
                        new
                        {
                            VideojuegoId = 10,
                            Anio = 2021,
                            Descripcion = "Forza Horizon 5 es un videojuego de carreras multijugador en línea desarrollado por Playground Games y publicado por Xbox Game Studios. Es el quinto título de Forza Horizon",
                            Poster = "https://m.media-amazon.com/images/I/71xPkgvw11L.__AC_SX300_SY300_QL70_ML2_.jpg",
                            Titulo = "Forza Horizon 5"
                        },
                        new
                        {
                            VideojuegoId = 11,
                            Anio = 2022,
                            Descripcion = "es un videojuego de simulación de carreras de 2022 desarrollado por Polyphony Digital y publicado por Sony Interactive Entertainment. El juego es la octava entrega principal de la serie Gran Turismo",
                            Poster = "https://m.media-amazon.com/images/I/81MdKU3FomL._AC_SX679_.jpg",
                            Titulo = "Gran Turismo 7"
                        },
                        new
                        {
                            VideojuegoId = 12,
                            Anio = 2014,
                            Descripcion = "es un videojuego de carreras de simulación desarrollado por Kunos Simulazioni. Está diseñado con énfasis en una experiencia de carreras realista con soporte para una amplia personalización y modificación. ",
                            Poster = "https://m.media-amazon.com/images/I/81A6KBrJBvL._AC_SX342_.jpg",
                            Titulo = "Assetto corsa"
                        },
                        new
                        {
                            VideojuegoId = 13,
                            Anio = 2019,
                            Descripcion = "Need for Speed Heat es juego de carreras ambientado en un entorno mundo abierto llamado Palm City, una versión ficticia de la ciudad de Miami, Florida.",
                            Poster = "https://m.media-amazon.com/images/I/71epK-pP+9L._AC_SX385_.jpg",
                            Titulo = "Need for Speed heat"
                        },
                        new
                        {
                            VideojuegoId = 14,
                            Anio = 2015,
                            Descripcion = "es un videojuego de lucha desarrollado por Bandai Namco Studios y Arika y publicado por Bandai Namco Entertainment. El juego se lanzó para PlayStation 5, Windows y Xbox Series X/S el 26 de enero de 2024",
                            Poster = "https://m.media-amazon.com/images/I/71N8vrjkr+L._AC_SX342_.jpg",
                            Titulo = "Resident Evil 4"
                        },
                        new
                        {
                            VideojuegoId = 15,
                            Anio = 2014,
                            Descripcion = "Alien: Isolation es un videojuego de terror tipo horror de supervivencia y sigilo en primera persona",
                            Poster = "https://m.media-amazon.com/images/I/81IIuRXbjoL._AC_SX569_.jpg",
                            Titulo = "Alien Isolation"
                        },
                        new
                        {
                            VideojuegoId = 16,
                            Anio = 2014,
                            Descripcion = "La historia sigue a Joel, un superviviente cansado y desesperado que ha perdido a su hija, y a Ellie, una joven de 14 años que ha sido infectada por el virus",
                            Poster = "https://m.media-amazon.com/images/I/71Ku7i1sXUL._AC_SX385_.jpg",
                            Titulo = "The Last Of us"
                        },
                        new
                        {
                            VideojuegoId = 17,
                            Anio = 2023,
                            Descripcion = "En Lethal Company, los jugadores obtienen y venden chatarra de exomoons abandonados e industrializados mientras evitan las trampas, los peligros ambientales y los monstruos",
                            Poster = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg?t=1700231592",
                            Titulo = "Lethal Company"
                        },
                        new
                        {
                            VideojuegoId = 18,
                            Anio = 1994,
                            Descripcion = "La trama del juego se centra en la situación que se ha dado tras la aparición en la anterior entrega del misterioso personaje Verse, cuyos poderes han llevado al regreso de muchos luchadores que habían muerto o desaparecido en el pasado.",
                            Poster = "https://m.media-amazon.com/images/I/81+PxnVvDeL._AC_SX569_.jpg",
                            Titulo = "The king of Fighers XV"
                        },
                        new
                        {
                            VideojuegoId = 19,
                            Anio = 2023,
                            Descripcion = "Street Fighter 6 presenta tres modos de juego generales: Fighting Ground, World Tour y Battle Hub. Fighting Ground contiene batallas versus locales y en línea, así como modos de entrenamiento y arcade",
                            Poster = "https://m.media-amazon.com/images/I/91t8mF84tEL._AC_SX522_.jpg",
                            Titulo = "Street Fighter 6"
                        },
                        new
                        {
                            VideojuegoId = 20,
                            Anio = 2018,
                            Descripcion = "Como todos los juegos de Soulcalibur anteriores a esta entrega, las peleas de Soulcalibur VI tienen lugar en un ambiente tridimensional, donde los luchadores se enfrentan con varios tipos de armas.",
                            Poster = "https://m.media-amazon.com/images/I/712tzVpRppL._AC_SX569_.jpg",
                            Titulo = "Soulcalibur 6"
                        },
                        new
                        {
                            VideojuegoId = 21,
                            Anio = 2024,
                            Descripcion = "es un videojuego de lucha desarrollado por Bandai Namco Studios y Arika y publicado por Bandai Namco Entertainment. El juego se lanzó para PlayStation 5, Windows y Xbox Series X/S el 26 de enero de 2024",
                            Poster = "https://m.media-amazon.com/images/I/812ymCiKznL._AC_SX385_.jpg",
                            Titulo = "Tekken 8"
                        });
                });

            modelBuilder.Entity("CategoriaVideojuego", b =>
                {
                    b.HasOne("tw.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tw.Models.Videojuego", null)
                        .WithMany()
                        .HasForeignKey("VideojuegosVideojuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tw.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tw.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tw.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tw.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
